# Generated by Django 5.2.13 on 2026-04-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vreme', models.DateTimeField()),
                ('trajanje_minuta', models.IntegerField(default=30)),
                ('slobodan', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termini',
                'ordering': ['datum_vreme'],
            },
        ),
        migrations.CreateModel(
            name='Pacijent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('datum_rodjenja', models.DateField(blank=True, null=True)),
                ('adresa', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pacijent',
                'verbose_name_plural': 'Pacijenti',
            },
        ),
        migrations.CreateModel(
            name='Pregled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta_pregleda', models.CharField(choices=[('RTG', 'Rentgen'), ('UZV', 'Ultrazvuk'), ('CT', 'CT Sken'), ('MRI', 'Magnetna rezonanca')], max_length=10)),
                ('status', models.CharField(choices=[('zakazan', 'Zakazan'), ('zavrsen', 'Završen'), ('otkazan', 'Otkazan')], default='zakazan', max_length=20)),
                ('napomena', models.TextField(blank=True)),
                ('kreiran', models.DateTimeField(auto_now_add=True)),
                ('pacijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregledi', to='termini.pacijent')),
                ('termin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='termini.termin')),
            ],
            options={
                'verbose_name': 'Pregled',
                'verbose_name_plural': 'Pregledi',
                'ordering': ['-termin__datum_vreme'],
            },
        ),
    ]
