# Generated by Django 5.2.13 on 2026-04-26 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termini', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacijent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacijent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specijalnost', models.CharField(default='Radiolog', max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doktor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktori',
            },
        ),
        migrations.AddField(
            model_name='pregled',
            name='doktor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregledi', to='termini.doktor'),
        ),
    ]
