# Generated by Django 5.2.13 on 2026-05-23 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termini', '0002_alter_pacijent_user_doktor_pregled_doktor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pacijent',
            name='pol',
            field=models.CharField(blank=True, choices=[('Muški', 'Muški'), ('Ženski', 'Ženski')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doktor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pregled',
            name='vrsta_pregleda',
            field=models.CharField(choices=[('RTG', 'Rendgen'), ('UZV', 'Ultrazvuk'), ('CT', 'CT Sken'), ('MRI', 'Magnetna rezonanca')], max_length=10),
        ),
    ]
